plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/arik/Projects/yalla-dubai-astro/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/attractions/%d7%a1%d7%a4%d7%90%d7%a8%d7%99-%d7%91%d7%9e%d7%93%d7%91%d7%a8-%d7%95%d7%98%d7%99%d7%95%d7%9c-%d7%92%d7%a4%d7%99%d7%9d/"
to = "/desert-safari/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/ספארי-במדבר-וטיול-גפים/"
to = "/desert-safari/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%91%d7%95%d7%a8%d7%92-%d7%97%d7%9c%d7%99%d7%a4%d7%94/"
to = "/attractions/burj-khalifa-attraction/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/בורג-חליפה/"
to = "/attractions/burj-khalifa-attraction/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%91%d7%95%d7%a8%d7%92-%d7%90%d7%9c-%d7%a2%d7%a8%d7%91/"
to = "/attractions/burj-al-arab/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/בורג-אל-ערב/"
to = "/attractions/burj-al-arab/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%93%d7%99%d7%a0%d7%aa-%d7%92%d7%95%d7%9e%d7%99%d7%99%d7%a8%d7%94/"
to = "/attractions/madinat-jumeirah/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מדינת-גומיירה/"
to = "/attractions/madinat-jumeirah/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%94%d7%9e%d7%a1%d7%92%d7%93-%d7%94%d7%92%d7%93%d7%95%d7%9c-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/grand-mosque-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/המסגד-הגדול-בדובאי/"
to = "/attractions/grand-mosque-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%a1%d7%9c%d7%95%d7%9c-%d7%9e%d7%a8%d7%95%d7%a6%d7%99-%d7%a1%d7%95%d7%a1%d7%99%d7%9d-%d7%9e%d7%99%d7%99%d7%93%d7%9f/"
to = "/attractions/meydan-racecourse/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מסלול-מרוצי-סוסים-מיידן/"
to = "/attractions/meydan-racecourse/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a7%d7%a0%d7%99%d7%95%d7%9f-%d7%91%d7%95%d7%a8%d7%92%d7%95%d7%9e%d7%90%d7%9f/"
to = "/attractions/bur-juman-mall/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/קניון-בורגומאן/"
to = "/attractions/bur-juman-mall/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%94%d7%90%d7%98%d7%94-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/hatta-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/האטה-דובאי/"
to = "/attractions/hatta-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%a4%d7%a1%d7%98%d7%99%d7%91%d7%9c-%d7%a1%d7%99%d7%98%d7%99/"
to = "/attractions/dubai-festival-city/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/דובאי-פסטיבל-סיטי/"
to = "/attractions/dubai-festival-city/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%95%d7%a4%d7%a2-%d7%94%d7%90%d7%95%d7%a8%d7%95%d7%aa-%d7%91%d7%9e%d7%96%d7%a8%d7%a7%d7%94-%d7%a9%d7%9c-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/dubai-fountain-show/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מופע-האורות-במזרקה-של-דובאי/"
to = "/attractions/dubai-fountain-show/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%96%d7%a8%d7%a7%d7%95%d7%aa-%d7%94%d7%9e%d7%99%d7%9d-%d7%a9%d7%9c-%d7%94%d7%a4%d7%90%d7%9c%d7%9d/"
to = "/attractions/palm-fountain-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מזרקות-המים-של-הפאלם/"
to = "/attractions/palm-fountain-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%90%d7%99-%d7%91%d7%9c%d7%95-%d7%95%d7%95%d7%98%d7%a8%d7%a1/"
to = "/attractions/bluewaters-island/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/אי-בלו-ווטרס/"
to = "/attractions/bluewaters-island/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%94%d7%90%d7%95%d7%9e%d7%92%d7%94-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/omega-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/האומגה-בדובאי/"
to = "/attractions/omega-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%95%d7%96%d7%99%d7%90%d7%95%d7%9f-%d7%94%d7%90%d7%a9%d7%9c%d7%99%d7%95%d7%aa/"
to = "/attractions/museum-of-illusions-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מוזיאון-האשליות/"
to = "/attractions/museum-of-illusions-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%95%d7%96%d7%99%d7%90%d7%95%d7%9f-%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%90%d7%97%d7%93-%d7%94%d7%9e%d7%95%d7%96%d7%99%d7%90%d7%95%d7%a0%d7%99%d7%9d-%d7%94%d7%9e%d7%99%d7%95%d7%97%d7%93%d7%99/"
to = "/attractions/dubai-museum/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מוזיאון-דובאי-אחד-המוזיאונים-המיוחד/"
to = "/attractions/dubai-museum/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%90%d7%90%d7%95%d7%98%d7%9c%d7%98/"
to = "/attractions/dubai-outlet-mall/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/דובאי-אאוטלט/"
to = "/attractions/dubai-outlet-mall/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a6%d7%9c%d7%99%d7%9c%d7%95%d7%aa-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/diving-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/צלילות-בדובאי/"
to = "/attractions/diving-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%94%d7%90%d7%a7%d7%95%d7%95%d7%a8%d7%99%d7%95%d7%9d-%d7%a9%d7%9c-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/dubai-aquarium/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/האקווריום-של-דובאי/"
to = "/attractions/dubai-aquarium/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9c%d7%92%d7%95%d7%9c%d7%a0%d7%93-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/legoland-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/לגולנד-דובאי/"
to = "/attractions/legoland-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9b%d7%95%d7%9b%d7%91-%d7%94%d7%9c%d7%9b%d7%aa-%d7%94%d7%99%d7%a8%d7%95%d7%a7/"
to = "/attractions/green-planet-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/כוכב-הלכת-הירוק/"
to = "/attractions/green-planet-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%95%d7%96%d7%99%d7%90%d7%95%d7%9f-%d7%90%d7%98%d7%99%d7%94%d7%93/"
to = "/attractions/etihad-museum-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מוזיאון-אטיהד/"
to = "/attractions/etihad-museum-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a4%d7%90%d7%a8%d7%a7-%d7%9e%d7%99%d7%9d-%d7%95%d7%95%d7%99%d7%99%d7%9c%d7%93-%d7%95%d7%95%d7%90%d7%93%d7%99/"
to = "/attractions/wild-wadi-waterpark/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/פארק-מים-וויילד-וואדי/"
to = "/attractions/wild-wadi-waterpark/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a4%d7%90%d7%a8%d7%a7-%d7%94%d7%9e%d7%99%d7%9d-%d7%9c%d7%92%d7%95%d7%9c%d7%a0%d7%93/"
to = "/attractions/legoland-waterpark/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/פארק-המים-לגולנד/"
to = "/attractions/legoland-waterpark/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%91%d7%95%d7%9c%d7%99%d7%95%d7%95%d7%93-%d7%a4%d7%90%d7%a8%d7%a7/"
to = "/attractions/bollywood-parks-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/בוליווד-פארק/"
to = "/attractions/bollywood-parks-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a0%d7%97%d7%9c-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/dubai-creek/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/נחל-דובאי/"
to = "/attractions/dubai-creek/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a4%d7%90%d7%a8%d7%a7-%d7%a9%d7%a2%d7%a9%d7%95%d7%a2%d7%99%d7%9d-%d7%9e%d7%95%d7%a9%d7%a0%d7%92%d7%99%d7%99%d7%98/"
to = "/attractions/motiongate-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/פארק-שעשועים-מושנגייט/"
to = "/attractions/motiongate-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%95%d7%a4%d7%a2-%d7%9c%d7%94-%d7%a4%d7%a8%d7%9c-%d7%94%d7%9e%d7%95%d7%a4%d7%a2-%d7%94%d7%9e%d7%98%d7%95%d7%a8%d7%a3-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/la-perle-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מופע-לה-פרל-המופע-המטורף-בדובאי/"
to = "/attractions/la-perle-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%98%d7%99%d7%a1%d7%aa-%d7%9e%d7%a1%d7%95%d7%a7-%d7%91%d7%a9%d7%9e%d7%99%d7%99-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/helicopter-tour-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/טיסת-מסוק-בשמיי-דובאי/"
to = "/attractions/helicopter-tour-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%98%d7%99%d7%95%d7%9c-rzr-%d7%91%d7%93%d7%99%d7%95%d7%a0%d7%95%d7%aa-%d7%a9%d7%9c-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/rzr-dune-tour-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/טיול-rzr-בדיונות-של-דובאי/"
to = "/attractions/rzr-dune-tour-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%94%d7%9e%d7%a8%d7%99%d7%a0%d7%94-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/dubai-marina/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/המרינה-בדובאי/"
to = "/attractions/dubai-marina/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%94%d7%9b%d7%a4%d7%a8-%d7%94%d7%92%d7%9c%d7%95%d7%91%d7%90%d7%9c%d7%99-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/global-village-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/הכפר-הגלובאלי-בדובאי/"
to = "/attractions/global-village-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%9e%d7%a1%d7%92%d7%a8%d7%aa-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/dubai-frame/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/מסגרת-דובאי/"
to = "/attractions/dubai-frame/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%92%d7%9f-%d7%94%d7%a4%d7%a8%d7%97%d7%99%d7%9d-%d7%94%d7%a4%d7%9c%d7%90%d7%99/"
to = "/attractions/miracle-garden-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/גן-הפרחים-הפלאי/"
to = "/attractions/miracle-garden-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a7%d7%a0%d7%99%d7%95%d7%9f-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/dubai-mall-attraction/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/קניון-דובאי/"
to = "/attractions/dubai-mall-attraction/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a1%d7%a7%d7%99-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/ski-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/סקי-דובאי/"
to = "/attractions/ski-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%a7%d7%99%d7%99%d7%98-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/attractions/kite-beach-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/קייט-בדובאי/"
to = "/attractions/kite-beach-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/%d7%90%d7%95%d7%98%d7%95%d7%93%d7%a8%d7%95%d7%9d-%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%9e%d7%a1%d7%9c%d7%95%d7%9c-%d7%9e%d7%99%d7%a8%d7%95%d7%a6%d7%99-%d7%9e%d7%9b%d7%95%d7%a0%d7%99%d7%95%d7%aa/"
to = "/attractions/dubai-autodrome/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/attractions/אוטודרום-דובאי-מסלול-מירוצי-מכוניות/"
to = "/attractions/dubai-autodrome/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%94%d7%99%d7%9b%d7%9f-%d7%9c%d7%a9%d7%94%d7%95%d7%aa-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%95%d7%9c%d7%99%d7%94%d7%a0%d7%95%d7%aa-%d7%9e%d7%a0%d7%95%d7%a3-%d7%9e%d7%95%d7%a9%d7%9c%d7%9d/"
to = "/guides/where-to-stay-in-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%a1%d7%9c%d7%99%d7%91%d7%a1%d7%98%d7%a8-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%94%d7%9e%d7%93%d7%a8%d7%99%d7%9a-%d7%94%d7%a9%d7%9c%d7%9d-%d7%9c%d7%97%d7%92%d7%99%d7%92%d7%95%d7%aa-%d7%a1%d7%99/"
to = "/guides/new-years-eve-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%9b%d7%a8%d7%99%d7%a1%d7%9e%d7%a1-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/guides/christmas-in-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%9e%d7%96%d7%92-%d7%94%d7%90%d7%95%d7%95%d7%99%d7%a8-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%91%d7%99%d7%a0%d7%95%d7%90%d7%a8/"
to = "/guides/dubai-weather-january/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%9e%d7%96%d7%92-%d7%90%d7%95%d7%95%d7%99%d7%a8-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%91%d7%93%d7%a6%d7%9e%d7%91%d7%a8/"
to = "/guides/dubai-weather-december/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%9b%d7%a0%d7%99%d7%a1%d7%94-%d7%9c%d7%93%d7%95%d7%91%d7%90%d7%99-%d7%a2%d7%9d-%d7%93%d7%a8%d7%9b%d7%95%d7%9f-%d7%96%d7%a8/"
to = "/guides/entry-dubai-foreign-passport/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%90%d7%99%d7%96%d7%94-%d7%91%d7%92%d7%93%d7%99%d7%9d-%d7%9c%d7%95%d7%91%d7%a9%d7%99%d7%9d-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/guides/what-to-wear-in-dubai/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%a7%d7%91%d7%95%d7%a6%d7%aa-%d7%94%d7%95%d7%95%d7%90%d7%98%d7%a1%d7%90%d7%a4-%d7%a9%d7%9c-%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/%d7%aa%d7%a2%d7%a8%d7%95%d7%9b%d7%aa-%d7%90%d7%a7%d7%a1%d7%a4%d7%95-2020-%d7%91%d7%93%d7%95%d7%91%d7%90%d7%99/"
to = "/guides/dubai-lametayel-2025/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/home/"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/index.html"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]